### ISSUE TITLE
Ant Nests Spawning Too Many Ants

### ISSUE THREAD

**Issue by thegam3report** [EnderMediaDev/Ultra-Modded-Survival#15]
There is a game breaking bug. I got a couple ant nests from orespawn and put them outside my base. I went afk while my quarry was running and came back to like 6 fps and about 2000 ants. There seems to be no cap on the ant nests.

**Comment by Amaxter** [comment]
Seems to be an OreSPawn problem, I will look into whether it can be configured to be lessened.

**Comment by thegam3report** [comment]
Thanks.

**Comment by Amaxter** [comment]
Issue is unsolvable in OreSpawn it seems, I tried enabling "Less Lag", but the config is not very helpful s to what that actually does. Marking as won't fix, as it's OreSpawn's problem.
