### ISSUE TITLE
Shickaxe's

### ISSUE THREAD

**Issue by thegam3report** [EnderMediaDev/Ultra-Modded-Survival#16]
Will not count as a pick for ores that are not Vanilla ores. It also won't work with tree capacitator on trees. Also doesn't break machines with the right efficiency so just seems to be incompatible with other mods.

**Comment by Amaxter** [comment]
They're being worked on for 1.4.1 of Divine RPG, so not fixable for the moment but coming.

**Comment by thegam3report** [comment]
Yay!
