### ISSUE TITLE
Will not load worlds

### ISSUE THREAD

**Issue by Gapydude** [EnderMediaDev/Ultra-Modded-Survival#17]
Whenever I create a world, it takes a while to create it. Afterwords, the minecraft client shuts down immediately and goes back to the Technic Launcher. Whenever I try to load that world, the same thing happens. It says "Shutting Down Internal Servers", then quits.

**Comment by Amaxter** [comment]
This isn't a modpack issue, you are somehow not allocating enough RAM likely. This doesn't belong here, it belongs in discussion as a crash report on pastebin. Closing.
