### ISSUE TITLE
Ender IO

### ISSUE THREAD

**Issue by thegam3report** [EnderMediaDev/Ultra-Modded-Survival#18]
Just today Captain was streaming and he goes "do we have the swag mill and alloy smelter?" Only to realise Ender IO isn't in the pack. he said we should really add that to the pack and then he talked about big reactors which is what I noticed too. Lol so does this mean you will add those 2?

**Comment by Amaxter** [comment]
Once he does, I will. Thanks for letting me know.

**Comment by Amaxter** [comment]
Leaving this open and will close and let you know when I do add it (once he adds it to the series).

**Comment by thegam3report** [comment]
No problem. He even said he was going to message you about it.

**Comment by thegam3report** [comment]
Thanks

**Comment by Amaxter** [comment]
He as in CaptainSparklez said he was going to message ME? Nice joke, I wish that were true ;)

**Comment by thegam3report** [comment]
He said he was going to message the creator of the pack. Isn't that you?

**Comment by Amaxter** [comment]
Yes, but he did he series then I made the pack. For all I know he doesn't even know I exist.

**Comment by thegam3report** [comment]
Well who was he referring to then? when he said he was going to message the maker of the pack.

**Comment by Amaxter** [comment]
Good question, but the person who makes the pack for his series is not me, I make the pack that people can play publically (and to be honest mine is likely higher quality as it’s my focus).

**Comment by thegam3report** [comment]
Yours is way higher quality. Since you are fixing the bugs that are game breaking such as the dmg cap, shickaxe etc. I love you <3

**Comment by Amaxter** [comment]
<3, let’s hope one day the Captain finds out the awesomeness taking place here :)

**Comment by ciak2009** [comment]
We're glad you're enjoying it!

**Comment by thegam3report** [comment]
Thanks :)

**Comment by xJon** [comment]
We will add the mods next update! Thanks for suggesting

**Comment by thegam3report** [comment]
np
