### ISSUE TITLE
Modpack not downloading

### ISSUE THREAD

**Issue by DashingMan** [EnderMediaDev/Ultra-Modded-Survival#19]
I have an issue, when i click on install, the modpack starts to download, but when it gets to nevermine (about 35%) the download gets stuck there and after a while it stops and i don't get the play button, i get the install button again. I've tried deleting and reinstalling it, i've updated my java and allocated 4GB of RAM. Also my internet is not slow, What should i do?

**Comment by Amaxter** [comment]
Your internet likely has some issues. Unrelated to the modpack. Closing. Good luck and I hope you find a way to fix it, but it's a problem on your end, and as such doesn't belong on this GitHub.
