### ISSUE TITLE
Recipe conflicts 

### ISSUE THREAD

**Issue by whitepyros** [EnderMediaDev/Ultra-Modded-Survival#20]
The mod to allow players to pick what is crafted when two or more items have the same crafting recipe can be found here updated to 1.7.10 http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287599-gotolink-updates-formivores-fixes-2015-06-13-and#RecipeHandler

**Comment by xJon** [comment]
We will add it next update! Thanks :)
