### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by thegam3report** [EnderMediaDev/Ultra-Modded-Survival#21]
When my friends try to start a single player now. The pack crashes and they can't play the world. It is also happening to me if I try to start a new one. My original world is fine.

**Comment by Amaxter** [comment]
Crash reports or it didn’t happen.

**Comment by thegam3report** [comment]
http://pastebin.com/hTid58A9

**Comment by Amaxter** [comment]
That’s odd, it’s an NEI crash. You must have screwed up some configuration for it, try reinstalling the pack.

**Comment by thegam3report** [comment]
i did not touch nei config but ok. I'll let them know too thanks.

**Comment by Amaxter** [comment]
Ok, good luck, Closing this :)

**Comment by thegam3report** [comment]
I figured out what the problem was for my friends completely unrelated to me. They are idiots. Basically they forgot to dedicate more ram to the pack and it was on 1Gb. As we know modded minecraft takes atleast 2.5GB. So problem solved and now it loads lol. Sorry man.

**Comment by Amaxter** [comment]
Nice :) glad you solved it

**Comment by thegam3report** [comment]
:)
