### ISSUE TITLE
Extra utils portals dont work

### ISSUE THREAD

**Issue by whitepyros** [EnderMediaDev/Ultra-Modded-Survival#22]
This is a bug casued by galacticraft and can easily be fixed by adding player api

http://wiki.micdoodle8.com/wiki/Compatibility#Any_other_mod_with_.27Fake_Player.27_detection

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996-player-api

**Comment by xJon** [comment]
Thanks! this fix is indeed working, and we will be sure to add PlayerAPI in the next update of our modpacks.
