### ISSUE TITLE
AE2

### ISSUE THREAD

**Issue by thegam3report** [EnderMediaDev/Ultra-Modded-Survival#23]
I believe you are using an outdated version of applied energistics 2 in the pack. The way I noticed this was today CS streamed the pack and his ae2 has crystal growth accelerator chamber which isn't in our version of ae2. It would be great if you could fix this and update ae2 in the next update of the pack :)
Thanks.

**Comment by Amaxter** [comment]
Haha, we're using the latest stable build of AE2, I'll look into where the crystal growth accelerator comes from but all our mods are latest :)

**Comment by thegam3report** [comment]
It's not the accelerators. it's the chamber, the recipe takes 6 accelerators to make it.

**Comment by thegam3report** [comment]
I did a quick googling it's called crystal growth chamber from ae2 stuff. So I guess his build of the pack has that mod. Hope that helps clarify

**Comment by Amaxter** [comment]
Ok. I will add AE2 Stuff for next build, thanks for notifying me.

**Comment by thegam3report** [comment]
Np. :)

**Comment by Amaxter** [comment]
Has been added.
