### ISSUE TITLE
youve probably got this a lot, but i crash every time i log on to single player

### ISSUE THREAD

**Issue by DragonMaster260** [EnderMediaDev/Ultra-Modded-Survival#24]
Heres my report

http://pastebin.com/Pdcy3jMf

ive tried adding more ram (i have 3.5 gigs) and ive tried a lot of other lings that im too lazy to list.
Please help me it would be nice because i really want to make the spawn for the server!

**Comment by Amaxter** [comment]
Update your Java, that fixes that crash.

**Comment by DragonMaster260** [comment]
thanks
