### ISSUE TITLE
DivineRPG

### ISSUE THREAD

**Issue by thegam3report** [EnderMediaDev/Ultra-Modded-Survival#26]
I was doing all the dimensions for DivineRPG and I got to the 8th one Vethea. When I was going through it my mobs stopped moving and my fps was going from 180 etc to 0 and 3. My minecraft basically stopped responding and locked up. When I got back on I was able to walk around again for like 10 seconds before the same thing happened. After multiple restarts I was able to get out and now my fps is fine again. I have no crash report cause it wasn't actually crashing. Is this fixable? I would really like to fight the 7 bosses from Vethea.

**Comment by Amaxter** [comment]
Logs?

**Comment by thegam3report** [comment]
The logs for that day is 338MB because of how much I played and it won't open lol.

**Comment by Amaxter** [comment]
According to the devs it's unfixable as Vethea is a very resource intensive dimension. The best thing you can do is allocate as much RAM as you safely can (I wouldn't go above 6 GB) and turn your render distance really low.

**Comment by thegam3report** [comment]
Thanks for the tips.

**Comment by Amaxter** [comment]
Np

**Comment by thegam3report** [comment]
The advice has helped a lot. Now I am actually able to do it :)

**Comment by Amaxter** [comment]
Good to hear :)
