### ISSUE TITLE
DivineRPG

### ISSUE THREAD

**Issue by thegam3report** [EnderMediaDev/Ultra-Modded-Survival#27]
I made the changes. I dedicated 6gb of ram. I was able to walk around vethea for a bit but then my chunks just stopped loading even thou my fps was 600. I had my render distance on 2. I tried changing all video settings to off, minimal and fast. I tried to exit my world and it was on closing server for like 30 minutes. Now when I try to get back on I have like a 5x5 of chunks loaded around me but nothing else loads and I just fall through the world. I have left it for an hour and it just doesn't load. I can't get back to my portal to get out. I tried /kill. My fps is fine and my cpu usage was only like 50%.

**Comment by Amaxter** [comment]
Try turning your render distance back up?

**Comment by thegam3report** [comment]
I have.

**Comment by Amaxter** [comment]
Then restore from backup via Aroma Backup.

**Comment by thegam3report** [comment]
Alright I'll look into that and update u

**Comment by Amaxter** [comment]
Ok, thanks.

**Comment by thegam3report** [comment]
I am extremely lucky. My 2 oldest backups possible were ok. So I had 1 from 2 days before I went to the dimension meaning no divine rpg stuff was done at all and the 2nd backup was literally 15 minutes before going into the vethea dimension and screwing my world so I am exactly where I was before that dimension. Thanks for the help again Amaxter. You are great <3

**Comment by Amaxter** [comment]
Np :)
