### ISSUE TITLE
Project Red Chip Filter Crash

### ISSUE THREAD

**Issue by DocTran** [EnderMediaDev/Ultra-Modded-Survival#29]
Hey posted this on the Technic discuss, you asked for it here.

Howdy, i was getting this error when using the pack and trying to filter a Project red chip. https://github.com/MrTJP/ProjectRed/issues/801 I was able to fix it by upgrading the Project Red Core and the 5 mods to the most recent version that was updated July 30th for 1.7.10. Just a heads!

**Comment by Amaxter** [comment]
Yep, will fix in an update tomorrow hopefully.
