### ISSUE TITLE
Servers

### ISSUE THREAD

**Issue by th3darknight531** [EnderMediaDev/Ultra-Modded-Survival#30]
Hello, just like the last UMS (the first one), you included popular servers for it by default on the multiplayer page. I was wondering if you can include Parcraft on it just as you did for the Parcraft server on the first UMS. Zeloz was thinking about making a server on the modpack, but the only way to publicize the server is to include it on this modpack.  Is there a way to include the server on the list? 

~Thank You

**Comment by Amaxter** [comment]
We're not doing an unofficial list anymore.
