### ISSUE TITLE
Mod crashes after clicking "Play"

### ISSUE THREAD

**Issue by Jw98** [EnderMediaDev/Ultra-Modded-Survival#31]
Error : pastebin.com/BcmfWGLu

- I downloaded and installed Java 8 Update 51 (64 and 32 Bit) but it still doesn't work . 
- I tried re-installing the mod 10 times but it still doesn't work
- I installed Java 7 Update 51 just to test around and it still doesn't work . 
- I allocated 5GB of RAM and it still doesn't work
- Something I notice is that after I click play , it says "Installing Minecraft Assets" and closes my launcher and runs Java Platform Binary but closes after 300mb of memory loaded .

Sorry for the trouble , I really want to play the Modpack

**Comment by Amaxter** [comment]
Why is legacy Java fixer in the pack? That's not the same modpack. Closing this issue.

**Comment by Jw98** [comment]
It was there as people recommended that it will fix the issue I was having , however it did not . 
I removed it and it was still not working .

**Comment by Amaxter** [comment]
Show me the full log, I've never seen an issue thei strange before.

**Comment by Jw98** [comment]
I'm not sure if this is the full log but it's the log from the latest one
pastebin.com/zebb2Qaf

**Comment by Amaxter** [comment]
It doesn't appear to be a full log, do you get a crash report?

**Comment by Jw98** [comment]
No , the Java platform Binary just loads to 300mb and relaunch my Technic Launcher .

**Comment by Amaxter** [comment]
Does this happen for any other modpacks? If it restarts the launcher then it's an issue you might want to deal with Technic with.

**Comment by Jw98** [comment]
Sorry for the late reply , actually no , other modpack such works fine including vanilla version .

**Comment by Amaxter** [comment]
Still not an issue with the modpack. I'd talk to technic support of its relaunching the whole

Launcher. Good luck.

**Comment by xJon** [comment]
Are you using a cracked launcher?

**Comment by Jw98** [comment]
Nope , i'm using the one I downloaded from this website www.technicpack.net/download

**Comment by xJon** [comment]
Try to reinstall it then because you have missing libarties, also check that it's up to date (build 313).

**Comment by Jw98** [comment]
I give up , it still doesn't work T_T 
Thanks for the help guys !

**Comment by xJon** [comment]
Well that's the problem anyway, it has nothing to do with this modpack and you won't be able to launch any modpack with an up-to-date Forge with this launcher.
It's a known issue for people using cracked launchers.
