### ISSUE TITLE
UMS wont launch

### ISSUE THREAD

**Issue by justasxz** [EnderMediaDev/Ultra-Modded-Survival#32]
So iam trying to launch ums but when i press play it just refuses to start it downloads libraries and goes back to launcher i allocated 4 gb of ram i think thats enough i used both 7 and 8 java (i tried removing mods error still persists i even removed all files except bin for w/e reason i think problem is in bin folder http://pastebin.com/MLGdyqCU

sry new to github cant seem to find spoilers so i just pastebinned it. atm iam just deleting 10 mods and launching then if error persists i bring them back and delete other 10 it doesnt seem to help at all
same problem for my friend it might be not too god of pc but i dont think you need titan x and i7 6700 or smth

**Comment by justasxz** [comment]
found and issue modpack.jar i changed it and it launches sure it gives an error but it does launch so now gotta find why

**Comment by Amaxter** [comment]
Glad you found your issue, next time assume if you modify anything with the pack you're going to have problems :)

**Comment by justasxz** [comment]
no dude i found where it is but i havent found a fix and i didint modify i just put random stuff there until it seems to work i still need help

**Comment by Amaxter** [comment]
Reinstall the pack, I'm sorry but I don't really understand what you're saying. Reinstall and provide logs and real information. This is not a support page, this is for modpack issues, and no one else has this issue, so I'm skeptical.

**Comment by justasxz** [comment]
my friend has i tried reinstalling it twice iam telling forge is doing some nonsense i provided log in my first mesasge

**Comment by justasxz** [comment]
dude okey so what do i do ? it only launches with older forges but it gives an error that i need a newer forge after launching so there is no way i can solve it iam idiot at this stuff

**Comment by Amaxter** [comment]
Don't change anything, if you have a cracked launcher, outdated Java, or just plain potato PC then you may have problems. If you have any of those things I can't help you. Good luck.

**Comment by justasxz** [comment]
i have newest java an average pc wich can handle witcher 3 and gta 5 on 60 fps and a friends account wich he gave for me so i can use technic legally so what do i do ?

**Comment by Amaxter** [comment]
Give me what I asked for, logs.

**Comment by justasxz** [comment]
wich one there are 3 logs latest fml-latest-client fml-junk early setup i guess you need latest ? or fml latest client ?

**Comment by Amaxter** [comment]
Latest and latest client as pastebins should suffice (that's two separate pastebins).

**Comment by justasxz** [comment]
sure just let me reinstall so i can give you clear not modified logs at all

**Comment by justasxz** [comment]
thats the latest one 
http://pastebin.com/nqNQnnet
and its fml latest client
http://pastebin.com/RnsLQFij

**Comment by Amaxter** [comment]
You have missing sound files, it seems as if perhaps you don't have permissions for the directory the pack is downloading them into. Are you by chance on a guest account or running on a computer with parental controls? If so you may be out of luck.

**Comment by justasxz** [comment]
no i got admin rights and i launch it as adimin

**Comment by Amaxter** [comment]
Then I don’t know what to tell you. Good luck.

**Comment by justasxz** [comment]
but i got premission to play with modpack to make it work make changes etc ? ofc i wont share it or download for someone else i just the goddamn thing to work

**Comment by Amaxter** [comment]
Of course, it’s your computer. I wish you luck, sorry I couldn’t be of more help, but this place isn’t really for support for things on the user’s end.

**Comment by justasxz** [comment]
np dude i just gonna try over and over again and if i wont succeed i just gonna find similiar modpack and add missing mods good luck in your future too :)

**Comment by Amaxter** [comment]
Ok, well good luck and good bye :)
